#if 1 /* patchouli vrio-makefile */
#
# Makefile for the vRIO modules
#
obj-m  += eth/

obj-m  += generic/

obj-m  += iohyp/sdev/
obj-m  += ioguest/sdev/

obj-m  += iohyp/net/
obj-m  += ioguest/net/

#endif
